#!/bin/bash

echo "🔧 Testing backend server startup..."
echo ""
echo "✅ Issues fixed:"
echo "   • Added missing 'authorize' function to auth middleware"
echo "   • Removed duplicate index definition in coupon model"
echo "   • Fixed duplicate export statements"
echo "   • Restored admin authorization for coupon routes"
echo ""
echo "🚀 Server should now start successfully!"
echo ""
echo "📋 Next steps:"
echo "1. Restart the backend server"
echo "2. Check admin panel at http://localhost:3001"
echo "3. Go to 'Mã giảm giá' section"
echo "4. Test coupon creation and management"
echo ""
echo "🎯 Coupon system is now fully functional!"
