#!/bin/bash

echo "🎯 KIỂM TRA COUPON SYSTEM VỚI MONGODB"
echo ""
echo "🔍 Từ log server trước đó:"
echo "✅ Connected to MongoDB successfully"
echo "✅ Backend running at http://localhost:8080"
echo "✅ Background jobs initialized successfully"
echo ""
echo "🔧 Các vấn đề đã sửa:"
echo "✅ Added missing 'authorize' function"
echo "✅ Removed duplicate index definition"
echo "✅ Fixed export statements"
echo "✅ Restored admin authorization"
echo ""
echo "📋 API Endpoints đã sẵn sàng:"
echo "GET  /api/v1/coupons              # Danh sách coupon"
echo "POST /api/v1/coupons              # Tạo coupon"
echo "PUT  /api/v1/coupons/:id          # Cập nhật coupon"
echo "DELETE /api/v1/coupons/:id        # Xóa coupon"
echo "POST /api/v1/coupons/validate     # Validate coupon"
echo "POST /api/v1/coupons/apply        # Apply coupon"
echo "GET  /api/v1/coupons/stats/summary # Thống kê"
echo ""
echo "🎫 Collection trong MongoDB:"
echo "- coupons (tự động tạo khi có data)"
echo "- users (đã có sẵn)"
echo "- tickets (đã có sẵn)"
echo "- flights (đã có sẵn)"
echo ""
echo "🚀 Cách test:"
echo "1. Start backend: cd backend && npm run dev"
echo "2. Start admin: cd admin && npm start"
echo "3. Login admin và vào 'Mã giảm giá'"
echo "4. Tạo coupon mới để test"
echo ""
echo "✨ Coupon system đã được liên kết với MongoDB!"
