
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "123456tu@gmail.com",
    "password": "123456"
}

### get profile
GET http://localhost:8080/api/v1/auth/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM2OGIyNDJkZDRjZjA4MDhlYWYxNzkiLCJlbWFpbCI6IjEyMzQ1NnR1QGdtYWlsLmNvbSIsImlhdCI6MTc1Nzg0MzE0NywiZXhwIjoxNzU3OTI5NTQ3fQ.OiXSiH3fpRYsnV4-k_0tBKTSd_k_J4ZrJgClnG7hMEY
