
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "123456tu@gmail.com",
    "password": "123456"
}

### get profile
POST http://localhost:8080/api/v1/auth/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGM2OGIyNDJkZDRjZjA4MDhlYWYxNzkiLCJlbWFpbCI6IjEyMzQ1NnR1QGdtYWlsLmNvbSIsImlhdCI6MTc1Nzg0Mjk4MywiZXhwIjoxNzU3OTI5MzgzfQ.lgS4NglOez0tYUyuknsOEOx7XTHz6D3hYjvA6tpeqag
