### Get all hotels
GET http://localhost:8080/api/v1/users

### Create new user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "fullName": "Hoàng Thiện Nhân",
    "email": "nhanvaddi@gmail.com",
    "phoneNumber": "0912345678",
    "password": "123456",
    "role": "user",
    "isActive": true
}

### Create admin user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "fullName": "Admin User",
    "email": "admindd@example.com",
    "phoneNumber": "0987654321",
    "password": "admin123",
    "role": "admin",
    "isActive": true
}
### Update user (thay thế :id bằng ID thực tế)
PUT http://localhost:8080/api/v1/users/68c63072a7aeb4a2436fc779
Content-Type: application/json

{
    "fullName": "Nguyen Van ddB",
    "phoneNumber": "0905123456"
}

### Delete user (thay thế :id bằng ID thực tế)
DELETE http://localhost:8080/api/v1/users/68c63072a7aeb4a2436fc779

